#!/usr/bin/env bash
# Auto-generate CMake list of interface definition files (msg and srv).
# This script scans the local msg/ and srv/ folders and writes a file
# "interface_files.cmake" containing CMake set() commands for MSG_FILES and
# SRV_FILES relative to the package root. Re-run when adding/removing interfaces.

set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${PKG_DIR}/interface_files.cmake"

collect_files() {
  local dir="$1" ext="$2"
  if [[ -d "$dir" ]]; then
    # Use LC_ALL=C for stable sort irrespective of locale.
    find "$dir" -maxdepth 1 -type f -name "*.${ext}" -printf '%f\n' | LC_ALL=C sort || true
  fi
}

msgs=( $(collect_files "${PKG_DIR}/msg" msg) ) || true
srvs=( $(collect_files "${PKG_DIR}/srv" srv) ) || true

{
  echo "# This file is auto-generated by generate_interface_lists.bash"
  echo "# Do not edit manually. Generated on $(date -u +'%Y-%m-%dT%H:%M:%SZ')."
  echo
  echo "set(MSG_FILES";
  for f in "${msgs[@]:-}"; do
    echo "  \"msg/${f}\"";
  done
  echo ")";
  echo
  echo "set(SRV_FILES";
  for f in "${srvs[@]:-}"; do
    echo "  \"srv/${f}\"";
  done
  echo ")";
  echo
} > "${OUT_FILE}.tmp"

# Only overwrite if changed to avoid unnecessary rebuild triggers.
if [[ ! -f "${OUT_FILE}" ]] || ! cmp -s "${OUT_FILE}.tmp" "${OUT_FILE}"; then
  mv "${OUT_FILE}.tmp" "${OUT_FILE}"
  [[ -n "${QUIET:-}" ]] || echo "[generate_interface_lists] Wrote ${OUT_FILE}"
else
  rm "${OUT_FILE}.tmp"
  [[ -n "${QUIET:-}" ]] || echo "[generate_interface_lists] No changes to ${OUT_FILE}"
fi
