# This file is auto-generated by generate_interface_lists.bash
# Do not edit manually. Generated on 2026-02-26T05:12:20Z.

set(MSG_FILES
  "msg/ControlOutput.msg"
  "msg/ManagerStatus.msg"
  "msg/PX4Status.msg"
  "msg/State.msg"
  "msg/TrajectorySetpoint.msg"
  "msg/UAVState.msg"
)

set(SRV_FILES
  "srv/Arm.srv"
  "srv/SetMode.srv"
)

set(ACTION_FILES
  "action/ExecuteTrajectory.action"
  "action/GoTo.action"
  "action/Land.action"
  "action/Takeoff.action"
)

