# This file is auto-generated by generate_interface_lists.bash
# Do not edit manually. Generated on 2025-10-09T10:29:20Z.

set(MSG_FILES
  "msg/PX4ActuatorCmd.msg"
  "msg/PX4TrajectorySetpoint.msg"
)

set(SRV_FILES
  "srv/MoveToPose.srv"
)

