/**:
  ros__parameters:
    # PX4 Gazebo default world origin (Zurich, Switzerland).
    # Keep this aligned with /opt/PX4-Autopilot/Tools/simulation/gz/worlds/default.sdf.
    home_lat_deg: 47.397971057728974
    home_lon_deg: 8.546163739800146
