/**:
  ros__parameters:
    publish_rate_hz: 100.0
    odometry_topic: "odometry"
    home_lat_deg: 47.397971
    home_lon_deg: 8.546164
    home_init_timeout_s: 90.0
    gps_min_fix_type: 3
    gps_min_satellites: 6
    gps_max_hdop: 5.0
    gps_max_vdop: 5.0
    gps_freshness_timeout_s: 2.0
