/**:
  ros__parameters:
    status_rate_hz: 5.0
    px4_status_timeout_s: 2.0
    manager_status_timeout_s: 1.0
    estimated_state_timeout_s: 1.0
    service_timeout_s: 8.0
    auto_start: true
    safety_status_timeout_s: 2.0
    require_external_safety: false
    data_readiness_poll_ms: 200
